# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'sinatra', '~>2.1.0'
gem 'thin', '~> 1.8', '>= 1.8.1'
gem 'puma', '~> 5.4'
gem 'reel', '~> 0.6.1'
gem 'http', '~> 5.0', '>= 5.0.1'
gem 'webrick', '~> 1.7'
gem 'json', '~> 2.5', '>= 2.5.1'
gem 'mysql', '~> 2.9', '>= 2.9.1'

